### ISSUE TITLE
SUGGESTION: badge when LocalStorage and/or SessionStorage is encountered

### ISSUE THREAD

**Issue by Cade66** [igorlogius/localstorage-editor#1]
Hi,

I've just discovered on AMO and run flawlessly _LocalStorage Editor_ 1.2.4 / Firefox 106.0.2
Perhaps a suggestion, that to add to the toolbar action-button a badge when LocalStorage and/or SessionStorage is encountered on a given page.
Similarly for instance to the _Cookie Autodelete_ extension does concerning cookies.

Otherwise, works nicely. Thanks.

**Comment by igorlogius** [comment]
I'm currently working on an UI overhaul, and have already take your request for an indicator for the active tab into consideration. 

![preview](https://user-images.githubusercontent.com/67047467/198877492-4d619c8e-d1b8-4ada-9f62-86a917f46804.png)

As you can see you can now determine at a glace if SessionStorage or LocalStorage data is available.

**Comment by Cade66** [comment]
Perfect! Now at a glance you can know if LocalStorage / SessionStorage is used by a page.
Like the cherry on the cake :=)
Staying tuned for update.

**Comment by igorlogius** [comment]
Version with indicator released.
